In [1]:
import pandas as pd
import numpy as np
import os
# import gc
from typing import Iterator, Union, List, Optional
from pathlib import Path
import shutil

In [4]:
# Read the CSV and extract column names as a list
cols = pd.read_csv("../columns.csv")["Column Names"].tolist()
parquet_files = [f for f in os.listdir('../planning_data/ped_report_parquet') if f.endswith('.parquet')]
parquet_files

[]

In [ ]:
dfs = []
for file in parquet_files:
    file_path = os.path.join('../planning_data/ped_report_parquet', file)
    arch_path = os.path.join('../planning_data/ped_report_parquet/archive', file)
    try:
        # Read the Excel file with specified columns
        df = pd.read_parquet(file_path, engine="pyarrow")
        print(f"Successfully read: {file}")
        dfs.append(df)
        print(f"Successfully appended: {file}")
        # Source path 
        dest = shutil.move(file_path, arch_path) 
    except Exception as e:
        print(f"Error reading {file}: {e}")
else:
    print("No valid data to save.")

if dfs:
    # Concatenate all DataFrames into one
    combined_df = pd.concat(dfs, ignore_index=True)
    
else:
    print("No Parquet files to process.")

Successfully read: 2020-03_WTC-PED-MONTHLY-RPT-v3.1.parquet
Successfully appended: 2020-03_WTC-PED-MONTHLY-RPT-v3.1.parquet
No valid data to save.

In [130]:
# combined_df
df = combined_df.drop_duplicates().reset_index(drop = True)
df

,From,To Time,Z01_T4-ChurchSt_RevDoor_IN,Z01_T4-ChurchSt_RevDoor_OUT,Z01_T4-ChurchSt_SwingDoor_IN,Z01_T4-ChurchSt_SwingDoor_OUT,Z02_T4-LibertySt_EastEsc46_IN,Z02_T4-LibertySt_EastEsc46_OUT,Z02_T4-LibertySt_WestEsc45_IN,Z02_T4-LibertySt_WestEsc45_OUT,...,Z27_T3TransitLobby_Stair50_DOWN_IN,Z27_T3TransitLobby_Stair50_UP_OUT,Z28_T3Elev-C1_OUTOFELEV_IN,Z28_T3Elev-C1_INTOELEV_OUT,Z28_1Train-C1-SConc_AllDoors_IN,Z28_1Train-C1-SConc_AllDoors_OUT,Z31_T3Elev-C2_OUTOFELEV_IN,Z31_T3Elev-C2_INTOELEV_OUT,Z29_C2_SWOculus_HubElev_OUTOFELEV,Z29_C2_SWOculus_HubElev_INTOELEV
0,2020-02-24 00:00:00,2020-02-24 00:05:00,1.0,0.0,0.0,0.0,0.0,1.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,1.0,0.0
1,2020-02-24 00:05:00,2020-02-24 00:10:00,0.0,0.0,3.0,0.0,0.0,1.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,2020-02-24 00:10:00,2020-02-24 00:15:00,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0
3,2020-02-24 00:15:00,2020-02-24 00:20:00,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0
4,2020-02-24 00:20:00,2020-02-24 00:25:00,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10651,2020-03-31 23:35:00,2020-03-31 23:40:00,0.0,0.0,0.0,1.0,0.0,1.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
10652,2020-03-31 23:40:00,2020-03-31 23:45:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,4.0,5.0,0.0,0.0
10653,2020-03-31 23:45:00,2020-03-31 23:50:00,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,4.0,3.0,0.0,0.0
10654,2020-03-31 23:50:00,2020-03-31 23:55:00,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10655,2020-03-31 23:55:00,2020-04-01 00:00:00,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
df_database = pd.read_parquet("../planning_data/database/database_cleaned.parquet", engine="pyarrow")
df_database

,Time_Bucket,Hub In/Out,Location - Monthly Ped Report,Zone Number,Count
0,2020-02-24 00:00:00,IN,1 Train North,23,1.0
1,2020-02-24 00:00:00,IN,1 Train North,30,9.0
2,2020-02-24 00:00:00,IN,1 Train South,28,0.0
3,2020-02-24 00:00:00,IN,1 Train South,29,3.0
4,2020-02-24 00:00:00,IN,2 WTC Transit Lobby,11,21.0
...,...,...,...,...,...
3707131,2024-08-31 23:30:00,OUT,PATH Turnstiles,21,0.0
3707132,2024-08-31 23:30:00,OUT,R/W Train North,25,38.0
3707133,2024-08-31 23:30:00,OUT,R/W Train South,22,7.0
3707134,2024-08-31 23:30:00,OUT,T3 Transit Lobby,27,10.0
3707135,2024-08-31 23:30:00,OUT,West Oculus Projection,5,25.0

In [132]:
df["Time_Bucket"] = df["From"].dt.floor("30T")  # "30T" means 30-minute interval
grouped_df = df.groupby("Time_Bucket").sum(numeric_only=True).reset_index()
long_df = grouped_df.melt(id_vars=["Time_Bucket"], var_name="Location", value_name="Count")
long_df

C:\Users\schew\AppData\Local\Temp\ipykernel_4664\2428167202.py:1: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  df["Time_Bucket"] = df["From"].dt.floor("30T")  # "30T" means 30-minute interval

               Time_Bucket                          Location  Count
0      2020-02-24 00:00:00        Z01_T4-ChurchSt_RevDoor_IN    1.0
1      2020-02-24 00:30:00        Z01_T4-ChurchSt_RevDoor_IN    0.0
2      2020-02-24 01:00:00        Z01_T4-ChurchSt_RevDoor_IN    0.0
3      2020-02-24 01:30:00        Z01_T4-ChurchSt_RevDoor_IN    2.0
4      2020-02-24 02:00:00        Z01_T4-ChurchSt_RevDoor_IN    1.0
...                    ...                               ...    ...
326779 2020-03-31 21:30:00  Z29_C2_SWOculus_HubElev_INTOELEV    0.0
326780 2020-03-31 22:00:00  Z29_C2_SWOculus_HubElev_INTOELEV    0.0
326781 2020-03-31 22:30:00  Z29_C2_SWOculus_HubElev_INTOELEV    0.0
326782 2020-03-31 23:00:00  Z29_C2_SWOculus_HubElev_INTOELEV    0.0
326783 2020-03-31 23:30:00  Z29_C2_SWOculus_HubElev_INTOELEV    0.0

[326784 rows x 3 columns]

In [5]:
sensor_mapping = pd.read_csv("../../Planning/Sensor_Mapping.csv")
sensor_mapping

,Sensor Number,Sensor Names,Weekly Avg Mapping,Hub In/Out,Exit Entry,Floor,Location - Monthly Ped Report,Location - Retail Report,Zone Description - Retail Report,Zone Number
0,1,Z01_T4-ChurchSt_RevDoor_IN,NaN,IN,NaN,NaN,NaN,NaN,NaN,1
1,2,Z01_T4-ChurchSt_RevDoor_OUT,NaN,OUT,NaN,NaN,NaN,NaN,NaN,1
2,3,Z01_T4-ChurchSt_SwingDoor_IN,NaN,IN,NaN,NaN,NaN,NaN,NaN,1
3,4,Z01_T4-ChurchSt_SwingDoor_OUT,NaN,OUT,NaN,NaN,NaN,NaN,NaN,1
4,5,Z02_T4-LibertySt_EastEsc46_IN,4.0,IN,Entries,Street Level,4 WTC Transit Lobby,NaN,NaN,2
...,...,...,...,...,...,...,...,...,...,...
179,180,Z28_1Train-C1-SConc_AllDoors_OUT,99.0,OUT,Exits,C1 Balcony Level,1 Train South,NaN,NaN,28
180,181,Z31_T3Elev-C2_OUTOFELEV_IN,NaN,IN,NaN,NaN,NaN,NaN,NaN,31
181,182,Z31_T3Elev-C2_INTOELEV_OUT,NaN,IN,NaN,NaN,NaN,NaN,NaN,31
182,183,Z29_C2_SWOculus_HubElev_OUTOFELEV,NaN,OUT,NaN,NaN,NaN,NaN,NaN,29
183,184,Z29_C2_SWOculus_HubElev_INTOELEV,NaN,IN,NaN,NaN,NaN,NaN,NaN,29

In [ ]:
long_df_join = long_df.merge(sensor_mapping, how = "left", left_on = "Location", right_on = "Sensor Names")
long_df_join_clean = long_df_join[["Time_Bucket","Sensor Names","Count","Hub In/Out","Location - Monthly Ped Report","Zone Number"]].dropna()
long_df_join_clean = long_df_join_clean.groupby(["Time_Bucket","Hub In/Out","Location - Monthly Ped Report","Zone Number"])["Count"].sum().reset_index()
re_concatenate = [df_database,long_df_join_clean]
combined_df = pd.concat(re_concatenate, ignore_index=True)
combined_df = combined_df.drop_duplicates()
parquet_filename = f"../planning_data/database/database_cleaned.parquet"
combined_df.to_parquet(parquet_filename, engine="pyarrow", index=False)